export const RendererInjectKey = Symbol("renderer")
export const WidthInjectKey = Symbol("width")
export const HeightInjectKey = Symbol("height")
export const SceneInjectKey = Symbol("scene")
export const CameraInjectKey = Symbol("camera")
