export const DeviceStatus = [
  //粗分线
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "N_P1", title: "P1", key: "P1" },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "N_P2", title: "P2", key: "P2", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "N_P3", title: "P3", key: "P3", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "N_P4", title: "P4", key: "P4", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "N_P5", title: "P5", key: "P5", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "LDJ_A", title: "梨刀机", key: "C_LDJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "ZMJ_A", title: "致密机", key: "C_ZMJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "CCYFJ_A", title: "致密机除尘器", key: "C_ZMJCCQ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "GLDZJ_A", title: "输送(致密机后)", key: "C_GLDZJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "SZJB_A", title: "混料", key: "C_SZJB", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "ZQQ_A", title: "造球机", key: "C_ZQJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "PDJ_A", title: "传送带", key: "C_PDJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "CCYFJ_A", title: "除尘器(造球)", key: "C_CCYFJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "ZQQ_A", title: "输送(造球区后)", key: "C_ZQQ", },
  {
    org: "atcc", bucket: "3fc_cf_sbzt", measurement: "T2", title: "T2", key: "T2",
    craft: { org: "atcc", bucket: "Mointor", measurement: "t2", title: "大窑T2工艺状态", key: "T2", },
  },
  {
    org: "atcc", bucket: "3fc_cf_sbzt", measurement: "DYCL_T", title: "红外", key: "T_DYCL",
    craft: { org: "atcc", bucket: "Mointor", measurement: "T_DYCL", title: "大窑红外工艺状态", key: "T_DYCL", },
  },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "DYSD_T", title: "红外", key: "T_DYSD", },
  {
    org: "atcc", bucket: "3fc_cf_sbzt", measurement: "T4", title: "T4", key: "T4",
    craft: { org: "atcc", bucket: "Mointor", measurement: "t4", title: "大窑T4工艺状态", key: "T4", },
  },
  {
    org: "atcc", bucket: "3fc_cf_sbzt", measurement: "T7", title: "T7", key: "T7",
    craft: { org: "atcc", bucket: "Mointor", measurement: "t7", title: "大窑T7工艺状态", key: "T7", },
  },
  {
    org: "atcc", bucket: "3fc_cf_sbzt", measurement: "T12", title: "T12", key: "T12",
    craft: { org: "atcc", bucket: "Mointor", measurement: "t12", title: "大窑T12工艺状态", key: "T12", },
  },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "YFJ_A", title: "引风", key: "C_YFJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "SJ_GeiFJ_P_Get_kPa", title: "给风机", key: "SJ_GeiFJ_P_Get_kPa", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "GFJ_A", title: "关风", key: "C_GFJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "SJ_YWFY_YL_Get_Pa", title: "窑尾负压", key: "SJ_YWFY_YL_Get_Pa", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "HZ_TRQ1_BKLL_GET_M3H", title: "天然气", key: "HZ_TRQ1_BKLL_GET_M3H", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "LQT_A", title: "冷却筒", key: "C_LQT", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "GuFJ_A", title: "鼓风机", key: "C_GuFJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "ZFG_T", title: "喷淋塔(T15)", key: "T_ZFG", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "WJZL_A", title: "外加籽料", key: "C_WJZL", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "CMJL_A", title: "输送(冷却后)	", key: "C_CMJL", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "CMJ_A", title: "干磨机", key: "C_CMJ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "CCYFJ_BPQ_A", title: "除尘器(干磨)", key: "C_CCYFJ_BPQ", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "GM_CCQCKFY_P_Get_kPa", title: "除尘器出口", key: "GM_CCQCKFY_P_Get_kPa", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "BZLX_A", title: "输送(干磨机后)", key: "C_BZLX", },
  { org: "atcc", bucket: "3fc_cf_sbzt", measurement: "ZDS_A", title: "振动筛", key: "C_ZDS", },


  //细粉线
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ14_A", title: "1#球磨机", key: "QMJ14_A" },
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ12_A", title: "2#球磨机", key: "QMJ12_A" },
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ10_A", title: "3#球磨机", key: "QMJ10_A" },
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ15_A", title: "4#球磨机", key: "QMJ15_A" },
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ17_A", title: "5#球磨机", key: "QMJ17_A" },
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ13_A", title: "6#球磨机", key: "QMJ13_A" },
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ11_A", title: "7#球磨机", key: "QMJ11_A" },
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ9_A", title: "8#球磨机", key: "QMJ9_A" },
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ16_A", title: "9#球磨机", key: "QMJ16_A" },
  { org: "atcc", bucket: "3fc_xf_sbzt", measurement: "QMJ18_A", title: "10#球磨机", key: "QMJ18_A" },
]
